# Generated by Django 5.1.7 on 2025-06-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_bill_bill_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu_item',
            new_name='furniture_item',
        ),
    ]
