# Generated by Django 5.1.7 on 2025-06-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_rename_menu_item_furniture_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='furniture_item',
            new_name='menu_item',
        ),
    ]
